### ISSUE TITLE
Pachyderm Crashes on File Writes

### ISSUE THREAD

**Issue by brendanacassidy** [jpoon/aurora_deploy#13]
pachyderm (specifically, pachd) as deployed via aurora_deploy.sh crashes and restarts when trying to write files to it.

This presented as the error "grpc: the connection is unavailable" in topach when pushing a shot, presumably because pachd restarting drops the grpc connection (between pachyderm and the go runtime pachyderm client in topach)

**Comment by JonathanFraser** [comment]
I've check that the credentials are being injected correctly into kubernetes, however the underlying container which pachyderm needs is not being created.

**Comment by jpoon** [comment]
Any errors from Pachyderm?

**Comment by JonathanFraser** [comment]
I'm afraid they aren't particularily helpful, only showing a disconnect themselves. I'll paste them here when I get back in the office.

**Comment by brendanacassidy** [comment]
The error I put in the issue description is the entirety of the error from
pachyderm.

**Comment by JonathanFraser** [comment]
This is all that kubectl logs is spitting out 
`
2016-11-18T17:47:25Z INFO  protoserver.ServerStarted {"port":650}
2016-11-18T17:47:25Z INFO  shard.StartRegister {"address":"10.244.0.3:650"}
2016-11-18T17:47:25Z INFO  shard.AddServerRole {"serverRole":{"address":"10.244.0.3:650","shards":{"0":true,"1":true,"2":true,"3":true,"4":true,"5":true,"6":true,"7":true,"8":true,"9":true,"10":true,"11":true,"12":true,"13":true,"14":true,"15":true,"16":true,"17":true,"18":true,"19":true,"20":true,"21":true,"22":true,"23":true,"24":true,"25":true,"26":true,"27":true,"28":true,"29":true,"30":true,"31":true}}}
2016/11/18 17:47:26 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.244.0.3:650: getsockopt: connection refused"; Reconnecting to {"10.244.0.3:650" <nil>}
2016-11-18T17:47:44Z INFO  protorpclog.Call {"service":"pachyderm.ppsclient.API","method":"ListPipeline","duration":"0.000s"}
2016-11-18T17:47:44Z INFO  protorpclog.Call {"service":"pachyderm.ppsclient.persist.API","method":"ListPipelineInfos","duration":"0.003757304s"}
2016-11-18T17:47:44Z INFO  protorpclog.Call {"service":"pachyderm.pps.persist.API","method":"ListPipelineInfos","duration":"0.004011511s"}
2016-11-18T17:47:44Z INFO  protorpclog.Call {"service":"pachyderm.ppsclient.API","method":"ListPipeline","duration":"0.004301619s"}
2016-11-18T17:47:44Z INFO  protorpclog.Call {"service":"pachyderm.pps.API","method":"ListPipeline","duration":"0.004856234s"}
2016-11-18T17:47:45Z INFO  shard.StartAssignRoles {}
`

**Comment by JonathanFraser** [comment]
nvm, there is a flag to get the logs from the previous container incarnation and there is much goodies to be had. looks like a panic originating in the azure sdk. First off why the hell is the azure sdk calling panic go code should NEVER do that (I'm really not liking this azure sdk). Second it looks like a linefeed has made its way into the container name for our deploy scripts. 

`
panic: parse https://aurorae2e8store%0A.blob.core.windows.net: invalid URL escape "%0A"

goroutine 92784790 [running]:
panic(0x169b5a0, 0xc420184ed0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/pachyderm/pachyderm/src/server/vendor/github.com/Azure/azure-sdk-for-go/storage.Client.getEndpoint(0x0, 0xc42041c240, 0x10, 0xc420552460, 0x40, 0x42, 0x1, 0x1844f6a, 0x10, 0x183b60b, ...)
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/Azure/azure-sdk-for-go/storage/client.go:195 +0x46d
github.com/pachyderm/pachyderm/src/server/vendor/github.com/Azure/azure-sdk-for-go/storage.BlobStorageClient.BlobExists(0x0, 0xc42041c240, 0x10, 0xc420552460, 0x40, 0x42, 0x1, 0x1844f6a, 0x10, 0x183b60b, ...)
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/Azure/azure-sdk-for-go/storage/blob.go:488 +0x13e
github.com/pachyderm/pachyderm/src/server/pkg/obj.(*microsoftClient).Exists(0xc420378620, 0xc4257cdf80, 0x64, 0x64)
	/go/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/microsoft_client.go:76 +0x8b
github.com/pachyderm/pachyderm/src/server/pfs/server.(*objBlockAPIServer).PutBlock.func3.1(0xc4257f2600, 0xc420114e60)
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/obj_block_api_server.go:167 +0xa0
github.com/pachyderm/pachyderm/src/server/vendor/github.com/cenkalti/backoff.RetryNotify(0xc420114e40, 0x2283580, 0xc4257f2600, 0x1914278, 0x8abe59, 0xc420cdb768)
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/cenkalti/backoff/retry.go:32 +0x3f
github.com/pachyderm/pachyderm/src/server/pfs/server.(*objBlockAPIServer).PutBlock.func3(0x8, 0x191b4a0)
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/obj_block_api_server.go:192 +0x14a
github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420114c80, 0xc420191920)
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/sync/errgroup/errgroup.go:66 +0x66

`

**Comment by JonathanFraser** [comment]
echo was injecting a line feed
fixed as of cf8e9b822
