### ISSUE TITLE
move from dockerhub to Azure Container Registry

### ISSUE THREAD

**Issue by brendanacassidy** [jpoon/aurora_deploy#14]
With the public preview of Azure Container Registry, we can move away from docker hub and have the images pulled down from an ACR that is specified as a top-level parameter. The auto-generated service principle should register itself to the ACR.

**Comment by jpoon** [comment]
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication

**Comment by brendanacassidy** [comment]
https://github.com/jpoon/aurora_deploy/pull/22
